import { db } from '../db/database'

const articleContent = [
  { slug: 'cosumaf', title: 'COSUMAF', category: 'Marché', simple: 'La COSUMAF supervise le marché financier de l’Afrique centrale.', definition: 'La Commission de Surveillance du Marché Financier de l’Afrique Centrale est l’autorité régionale de régulation des marchés financiers de la CEMAC.', example: 'La Commission publie des règlements et instructions applicables aux acteurs du marché.', formula: 'Sans objet.', interpretation: 'Ses textes encadrent l’agrément, le contrôle et l’information financière.', limitation: 'Chaque obligation doit être vérifiée contre le texte officiel à jour et les procédures de l’établissement.', source: 'Ressources et textes officiels COSUMAF.', ruleClass: 'OFFICIAL', verificationStatus: 'TO_VERIFY' },
  { slug: 'bvmac', title: 'BVMAC', category: 'Marché', simple: 'La BVMAC est la bourse régionale des valeurs mobilières de la CEMAC.', definition: 'La Bourse des Valeurs Mobilières de l’Afrique Centrale organise les cotations et diffuse les bulletins officiels de la cote.', example: 'Un bulletin quotidien indique les cours, volumes et indices disponibles à une séance.', formula: 'Sans objet.', interpretation: 'Les cours observés sont à distinguer des cours générés pour la démo.', limitation: 'BrokerControl360 ne transmet aucun ordre à la BVMAC.', source: 'Bulletins BVMAC fournis dans le projet.', ruleClass: 'OFFICIAL', verificationStatus: 'CONFIRMED' },
  { slug: 'cemac-et-beac', title: 'CEMAC et BEAC', category: 'Marché', simple: 'La CEMAC rassemble les États d’Afrique centrale et partage une monnaie commune, le FCFA BEAC.', definition: 'La Communauté Économique et Monétaire de l’Afrique Centrale comprend six États membres. La BEAC émet le franc CFA d’Afrique centrale (XAF).', example: 'Un portefeuille régional peut contenir des titres du Cameroun, du Gabon et du Congo, cotés en XAF.', formula: 'Sans objet.', interpretation: 'Le pays de l’émetteur et la devise du titre sont deux caractéristiques distinctes.', limitation: 'L’ISIN seul ne confirme pas la résidence juridique ou fiscale de l’émetteur.', source: 'BEAC et textes CEMAC.', ruleClass: 'OFFICIAL', verificationStatus: 'CONFIRMED' },
  { slug: 'opcvm-fcp-sicav', title: 'OPCVM, FCP et SICAV', category: 'Instruments', simple: 'Un OPCVM collecte l’épargne et l’investit selon une stratégie définie.', definition: 'Les organismes de placement collectif en valeurs mobilières incluent notamment les fonds communs de placement et les sociétés d’investissement à capital variable.', example: 'Un FCP monétaire publie une valeur liquidative selon une périodicité définie par sa documentation.', formula: 'Valeur de la part = actif net du fonds ÷ nombre de parts.', interpretation: 'Les valeurs liquidatives ne sont pas forcément calculées chaque séance boursière.', limitation: 'Le MVP affiche les VL des bulletins, sans souscription ou rachat réel.', source: 'Bulletins BVMAC et documentation de fonds.', ruleClass: 'MARKET_PRACTICE', verificationStatus: 'TO_VERIFY' },
  { slug: 'fcp', title: 'FCP', category: 'Instruments', simple: 'Le fonds commun de placement est une copropriété de valeurs mobilières sans personnalité morale.', definition: 'Les porteurs détiennent des parts représentatives d’actifs gérés par une société de gestion.', example: 'FCP AB CASH est présenté parmi les fonds affichés dans le bulletin de la séance.', formula: 'Nombre de parts × valeur liquidative publiée.', interpretation: 'Cette estimation ne tient pas compte de frais propres à une souscription ou un rachat.', limitation: 'Les conditions d’opération doivent être vérifiées dans le prospectus du fonds.', source: 'Bulletins et prospectus des fonds.', ruleClass: 'MARKET_PRACTICE', verificationStatus: 'TO_VERIFY' },
  { slug: 'isin-et-mnemonique', title: 'ISIN et mnémonique', category: 'Instruments', simple: 'L’ISIN identifie un titre et le mnémonique est son code de marché abrégé.', definition: 'L’ISIN suit une structure internationale d’identification des valeurs mobilières ; le mnémonique facilite leur reconnaissance à l’écran.', example: 'CM0000010009 est l’ISIN de l’action SEMC dans les bulletins fournis.', formula: 'ISIN : deux caractères de pays, neuf caractères nationaux, une clé de contrôle.', interpretation: 'Les contrôles s’appuient sur l’ISIN tandis que les utilisateurs recherchent souvent le mnémonique.', limitation: 'Une valeur d’ISIN dans un fichier ne prouve pas à elle seule l’authenticité du document.', source: 'ISO 6166 et référentiel BVMAC fourni.', ruleClass: 'MARKET_PRACTICE', verificationStatus: 'CONFIRMED' },
  { slug: 'duration-obligataire', title: 'Duration obligataire', category: 'Gestion et risque', simple: 'La duration estime la sensibilité du prix d’une obligation à un mouvement de taux.', definition: 'La duration de Macaulay est la moyenne pondérée des dates des flux. La duration modifiée approxime le changement relatif de prix.', example: 'Une duration modifiée de 4 implique une baisse approximative de 4% pour une hausse de rendement de 1 point, toutes choses égales par ailleurs.', formula: 'ΔP/P ≈ −Duration_modifiée × Δtaux.', interpretation: 'Plus la duration est forte, plus le prix est sensible aux taux.', limitation: 'L’approximation est linéaire et ignore convexité, défaut, options et changements de liquidité.', source: 'Formules usuelles de valorisation obligataire.', ruleClass: 'MARKET_PRACTICE', verificationStatus: 'CONFIRMED' },
  { slug: 'hhi-concentration', title: 'Concentration HHI', category: 'Gestion et risque', simple: 'Le HHI résume le poids relatif des plus grandes expositions.', definition: 'L’indice de Herfindahl-Hirschman est la somme des carrés des parts d’exposition exprimées en pourcentage.', example: 'Deux lignes égales à 50% chacune donnent un HHI de 5 000.', formula: 'HHI = Σ (poids_i en %)².', interpretation: 'Un indice supérieur reflète une concentration plus forte selon la granularité retenue.', limitation: 'Le HHI n’est pas un seuil réglementaire dans cette application et dépend du regroupement des expositions.', source: 'Mesure de concentration de portefeuille — indicateur pédagogique.', ruleClass: 'DEMO', verificationStatus: 'CONFIRMED' },
  { slug: 'nav-et-allocation', title: 'NAV et allocation', category: 'Gestion et risque', simple: 'La NAV est la valeur des positions et espèces à une date donnée.', definition: 'La valeur nette d’actif agrège les valorisations des instruments et soldes espèces, selon le périmètre retenu.', example: 'Valeur des titres 80 M FCFA + cash 20 M FCFA = NAV 100 M FCFA.', formula: 'NAV = Σ position × cours + espèces + autres postes retenus.', interpretation: 'L’allocation rapporte chaque catégorie à la NAV.', limitation: 'Les frais, coupons courus ou flux non saisis peuvent différer du calcul d’un teneur de compte.', source: 'Calcul local de démonstration BrokerControl360.', ruleClass: 'DEMO', verificationStatus: 'CONFIRMED' },
  { slug: 'twr-mwr-volatilite-var', title: 'Performance, volatilité et VaR', category: 'Gestion et risque', simple: 'Les indicateurs de performance et de risque synthétisent un historique, sans prédire le futur.', definition: 'TWR neutralise l’effet des flux externes ; MWR/XIRR tient compte de leur calendrier. Volatilité mesure la dispersion des rendements et VaR une perte quantile estimée.', example: 'Une VaR à 95% est une estimation de seuil de perte sur un horizon et un modèle définis.', formula: 'Volatilité annualisée ≈ écart-type des rendements × √(périodes/an).', interpretation: 'Les hypothèses et la période d’observation conditionnent fortement le résultat.', limitation: 'L’historique BVMAC disponible est court ; les métriques calculées ne sont pas une mesure robuste.', source: 'Méthodes usuelles de gestion de portefeuille.', ruleClass: 'MARKET_PRACTICE', verificationStatus: 'TO_VERIFY' },
  { slug: 'maker-checker', title: 'Maker-checker', category: 'Conformité', simple: 'Une personne prépare l’opération et une autre la contrôle.', definition: 'Le double contrôle sépare la création et l’approbation d’une opération pour renforcer la gouvernance interne.', example: 'L’auteur d’un ordre ne peut pas approuver le même ordre dans le parcours de démonstration.', formula: 'Règle UX : créateur ≠ approbateur.', interpretation: 'La piste d’audit garde les deux acteurs fictifs et les horodatages.', limitation: 'Les profils du navigateur ne sont pas des identités vérifiées ni une séparation de sécurité réelle.', source: 'Bonne pratique de contrôle interne, à valider localement.', ruleClass: 'MARKET_PRACTICE', verificationStatus: 'TO_VERIFY' },
  { slug: 'provenance-des-donnees', title: 'Provenance des données', category: 'Méthodologie', simple: 'Chaque donnée montre si elle vient d’un bulletin ou d’un calcul de démonstration.', definition: 'OBSERVED provient du bulletin, INTERPOLATED est calculé entre observations, SIMULATED est synthétique.', example: 'Les volumes sans transaction observée restent à zéro ; le prix simulé reçoit une graine documentée.', formula: 'Aucune.', interpretation: 'La couleur du badge et le nom de la source permettent de comprendre l’origine.', limitation: 'Une provenance OBSERVED décrit l’origine du fichier importé ; elle ne constitue pas une certification de la source.', source: 'Cahier des charges BrokerControl360, section gouvernance des données.', ruleClass: 'DEMO', verificationStatus: 'CONFIRMED' },
  { slug: 'rapprochement', title: 'Rapprochement positions et espèces', category: 'Opérations', simple: 'Le rapprochement compare les enregistrements internes à un relevé externe.', definition: 'Un rapprochement met en regard les positions titres, soldes espèces ou ordres entre deux sources et documente les écarts.', example: 'Une ligne présentant 1 000 titres en interne et 975 chez le dépositaire génère un écart de 25.', formula: 'Écart = solde interne − solde externe.', interpretation: 'Les anomalies ouvertes doivent être attribuées, commentées et résolues.', limitation: 'Le jeu externe est synthétique et n’est connecté ni à une banque ni au dépositaire.', source: 'Parcours de démonstration BrokerControl360.', ruleClass: 'DEMO', verificationStatus: 'CONFIRMED' },
  { slug: 'cosumaf-rapports', title: 'Rapports COSUMAF — périmètre', category: 'Conformité', simple: 'Les rapports fournis sont des maquettes de travail, pas des formulaires officiels.', definition: 'Le produit propose des tableaux et exports de contrôle inspirés des sujets de supervision mentionnés au cahier des charges.', example: 'Le rapport de limite regroupe seuil, exposition, écart et action de suivi.', formula: 'Les règles et champs dépendent du document officiel applicable.', interpretation: 'Un badge TO_VERIFY signale ce qui n’est pas encore confirmé avec la conformité.', limitation: 'Ne pas déposer ce rapport auprès d’une autorité comme document réglementaire validé.', source: 'Instruction COSUMAF n°39-25 et ressources citées au cahier des charges, à vérifier.', ruleClass: 'OFFICIAL', verificationStatus: 'TO_VERIFY' },
]

export async function ensureWiki() {
  if (await db.wikiArticles.count() > 0) return
  const categories = [...new Set(articleContent.map((article) => article.category))]
  const timestamp = new Date().toISOString()
  await db.transaction('rw', [db.wikiCategories, db.wikiArticles], async () => {
    await db.wikiCategories.bulkPut(categories.map((title) => ({ id: title.toLocaleLowerCase().replaceAll(' ', '-'), slug: title.toLocaleLowerCase().replaceAll(' ', '-'), title, createdAt: timestamp, updatedAt: timestamp })))
    await db.wikiArticles.bulkPut(articleContent.map((article) => ({
      ...article, id: article.slug, categoryId: article.category.toLocaleLowerCase().replaceAll(' ', '-'),
      summary: article.simple, professionalDefinition: article.definition,
      createdAt: timestamp, updatedAt: timestamp,
    })))
  })
}

export async function searchWiki(query: string) {
  const articles = await db.wikiArticles.toArray()
  const normalized = query.trim().toLocaleLowerCase()
  return articles.filter((article) => !normalized || `${article.title} ${article.category} ${article.summary} ${article.definition} ${article.example}`.toLocaleLowerCase().includes(normalized))
}
